title: Translate Documents
description: This Add-On allows you to translate documents using the Google Translate service. Supply a two character ISO 639-1 code for the input and output languages and you will receive your translation in a download as well as it will be uploaded to DocumentCloud. See https://www.loc.gov/standards/iso639-2/php/code_list.php for more details about ISO 639-1 codes.  
type: object
documents:
  - query
  - selected
properties:
  input_lang:
    title: Input language code
    type: string
    default: en
  output_lang:
    title: Output language code
    type: string
    default: es
required: 
  -input_lang
  -output_lang
