title: Translate Documents
description: This Add-On allows you to translate documents using the Google Translate service. Supply a two character ISO 639-1 code for the input and output languages and you will receive your translation in a download as well as it will be uploaded to DocumentCloud. See https://cloud.google.com/translate/docs/languages for supported languages.
type: object
documents:
  - selected
properties:
  input_lang:
    title: Input language code
    type: string
    default: en
    # enum reference:
    # https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values
    # yaml alias reference:
    # https://blog.daemonl.com/2016/02/yaml.html
    enum: &langs
      - af # Afrikaans 
      - sq # Albanian 
      - am # Amharic 
      - ar # Arabic 
      - hy # Armenian 
      - as # Assamese 
      - ay # Aymara 
      - az # Azerbaijani 
      - bm # Bambara 
      - eu # Basque 
      - be # Belarusian 
      - bn # Bengali 
      - bho # Bhojpuri 
      - bs # Bosnian 
      - bg # Bulgarian 
      - ca # Catalan 
      - ceb # Cebuano 
      - zh-CN # Chinese (Simplified) 
      - zh-TW # Chinese (Traditional) 
      - co # Corsican 
      - hr # Croatian 
      - cs # Czech 
      - da # Danish 
      - dv # Dhivehi 
      - doi # Dogri 
      - nl # Dutch 
      - en # English 
      - eo # Esperanto 
      - et # Estonian 
      - ee # Ewe 
      - fil # Filipino (Tagalog) 
      - fi # Finnish 
      - fr # French 
      - fy # Frisian 
      - gl # Galician 
      - ka # Georgian 
      - de # German 
      - el # Greek 
      - gn # Guarani 
      - gu # Gujarati 
      - ht # Haitian Creole 
      - ha # Hausa 
      - haw # Hawaiian 
      - he # Hebrew  or iw
      - hi # Hindi 
      - hmn # Hmong 
      - hu # Hungarian 
      - is # Icelandic 
      - ig # Igbo 
      - ilo # Ilocano 
      - id # Indonesian 
      - ga # Irish 
      - it # Italian 
      - ja # Japanese 
      - jv # Javanese  or jw
      - kn # Kannada 
      - kk # Kazakh 
      - km # Khmer 
      - rw # Kinyarwanda 
      - gom # Konkani 
      - ko # Korean 
      - kri # Krio 
      - ku # Kurdish 
      - ckb # Kurdish (Sorani) 
      - ky # Kyrgyz 
      - lo # Lao 
      - la # Latin 
      - lv # Latvian 
      - ln # Lingala 
      - lt # Lithuanian 
      - lg # Luganda 
      - lb # Luxembourgish 
      - mk # Macedonian 
      - mai # Maithili 
      - mg # Malagasy 
      - ms # Malay 
      - ml # Malayalam 
      - mt # Maltese 
      - mi # Maori 
      - mr # Marathi 
      - mni-Mtei # Meiteilon (Manipuri) 
      - lus # Mizo 
      - mn # Mongolian 
      - my # Myanmar (Burmese) 
      - ne # Nepali 
      - no # Norwegian 
      - ny # Nyanja (Chichewa) 
      - or # Odia (Oriya) 
      - om # Oromo 
      - ps # Pashto 
      - fa # Persian 
      - pl # Polish 
      - pt # Portuguese (Portugal, Brazil) 
      - pa # Punjabi 
      - qu # Quechua 
      - ro # Romanian 
      - ru # Russian 
      - sm # Samoan 
      - sa # Sanskrit 
      - gd # Scots Gaelic 
      - nso # Sepedi 
      - sr # Serbian 
      - st # Sesotho 
      - sn # Shona 
      - sd # Sindhi 
      - si # Sinhala (Sinhalese) 
      - sk # Slovak 
      - sl # Slovenian 
      - so # Somali 
      - es # Spanish 
      - su # Sundanese 
      - sw # Swahili 
      - sv # Swedish 
      - tl # Tagalog (Filipino) 
      - tg # Tajik 
      - ta # Tamil 
      - tt # Tatar 
      - te # Telugu 
      - th # Thai 
      - ti # Tigrinya 
      - ts # Tsonga 
      - tr # Turkish 
      - tk # Turkmen 
      - ak # Twi (Akan) 
      - uk # Ukrainian 
      - ur # Urdu 
      - ug # Uyghur 
      - uz # Uzbek 
      - vi # Vietnamese 
      - cy # Welsh 
      - xh # Xhosa 
      - yi # Yiddish 
      - yo # Yoruba 
      - zu # Zulu 
  output_lang:
    title: Output language code
    type: string
    default: es
    enum: *langs
  project_id: 
    title: Project ID
    type: integer 
    description: (Optional) Project ID of project you want to upload the translations to. 
  access_level: 
    title: Access level (public, private, organization) of translations
    type: string
    default: public
    enum: &access
      - public 
      - private
      - organization 
required:
  - access_level
  - output_lang
  - input_lang
